<a href="https://colab.research.google.com/github/niteshkumar0205/machine-learning-/blob/main/ml_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#NUMPY




In [ ]:
import numpy as np

a = [1,2,3,4,5]

arr1 = np.array(a)
b= [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(b)

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(type(a))
print(type(b))
print(type(arr1))
print(type(arr2))


<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
import sys
s = range(1000)

print("size of each elements in list in bytes",sys.getsizeof(s))

print("complete list size in bytes",sys.getsizeof(s)*len(s))

size of each elements in list in bytes 48
complete list size in bytes 48000


In [ ]:
import numpy as np

s = np.arange(1000)

print("size of each elements in the list by bytes ",s.itemsize)

print("complete list size in bytes",s.size * s.itemsize)

size of each elements in the list by bytes  8
complete list size in bytes 8000


In [ ]:
import time

a = range(1000)
b=range(1000)

start = time.time()

ab = [(a *b) for a,b in zip(a,b)]

end = time.time()

print("total time taken",end - start )

total time taken 0.00020122528076171875


In [ ]:
import numpy 
import time

arr1 = np.arange(1000)
arr2 = np.arange(1000)

start = time.time()

arr_mul  = arr1*arr2

end = time.time()

print(" total time taken", end- start)

 total time taken 7.987022399902344e-05


In [ ]:
lst1 = [1,2,3,4]

arr = np.array(lst1)

print(arr)

[1 2 3 4]


In [ ]:
arr1= np.array([[1,2,3,4],[5,6,7,8]])

print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr2 = list(arr1)

print(arr2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [ ]:
print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# creating n-d array

a = [[1,2,3],[4,5,6]]

print(a)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
import numpy as np

np.array(a,ndmin = 10)

array([[[[[[[[[[1, 2, 3],
               [4, 5, 6]]]]]]]]]])

In [ ]:
arr = np.array([[1,2,3],
               [2,3,4],
               [6,7,8]])
print(arr)

[[1 2 3]
 [2 3 4]
 [6 7 8]]


#PANDAS